export default  {

    new:"New",
    this_year:"This Year",
    last_2_year:"Last 2 Year",
    last_5_year:"Last 5 Year ",
    last_10_year:"Last 10 year",
    customized_text:"Customized",
    from_text:"From",
    to_text:"To",
    search:"Search title or artist",
    email_address:"email-address",
    similar_titles:"Similar titles:",
    best_movies:"BestMovies",
    movies_text:'Movies',
    tv_shows:"TV shows",
    shorts:"Shorts",
    directors:"Directors",
    actors:"Actors",
    include_previous_text:"Including Previously browsed",
    include_watching:"Include Watching",
    countries:"Countries",
    country_list:"USA,UK,France,Spain,Argentina,Italy,Canada,Germany",
    original_language:"Original Languages",
    all:"All",
    ages:"Age rating (max)",
    liked_by:"Liked By",
    streaming_service:"Streaming services",

    providers:"Providers",
    theaters:"+ theaters",
    three_rent:"+ 3 rent/buy",
    all_free:"+ all free (ads)",

    netflix_etc:"Netflix,Amazon Prime ,HBO,Flimin(Theaters included)",
    price:"Price",
    add_included:"(Add included)",
    linkedBy:"Linked by",
    clear_filter:"Clear Filters",
    my_provider:"My Provider",
    save_as_provider:'Save as MY Provider',
    movies_theater:"Movies theaters",
    subscription:"Subscriptions",
    rent_n_buy:"Rent & buy",
    country:"Countries of origin",
    genre:"Genres",
    my_lists:"My lists",
    watch_later:"Watch later",
    friends_rating:"Friends' ratings",
    my_ratings:"My ratings",
    great:"Great",
    awards_colon:"Awards:",
    audience:"Audience",
    critics:"Critics",
    box_office:"Box-office",
    sort_by:"Sort By",
    rating:"Rating",
    release:"Release year",
    include:"Include Watched",
    about_us: "About us",
    advertise: "Advertise",
    collaborate: "Collaborate",
    jobs: "Jobs",
    terms_of_use: "Terms of use",
    privacy_policy: "Privacy Policy",
    notification:"Notification",
    friends: "Friends",
    preferences: "Preferences",
    my_providers:"My providers",
    account: "Account",
    language: "Language",
    country_language : "Country & Language",
    mobile_app : "Mobile app",
    invite_friend : "Invite friend",



    

}