export const SET_COUNTER = "SET_COUNTER"
export const INCREASE_COUNTER = "INCREASE_COUNTER"
export const DECREASE_COUNTER = "DECREASE_COUNTER"

export const SET_CURR_FOCUS = "SET_CURR_FOCUS"
export const RESET_CURR_FOCUS = "RESET_CURR_FOCUS"
